# NumPy - Multiplication and Array Broadcasting
This jupyter notebook presents two useful Linear Algebra operations by NumPy

### Part A - Multiplication between N-dimensional arrays

We describe the techniques for multiplying N-dimesional arrays using NumPy. Specifically we describe the follwing types of multiplications: 
    * Element-wise multiplication (Hadamard product)
    * Dot product
    * matrix multiplication
    <br>
<b>We'll start by importing NumPy</b>

In [1]:
import numpy as np

### Element-wise multiplication (Hadamard product)

The element-wise product or Hadamard product is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands, where each element i, j is the product of elements i, j of the original two matrices.

We can use the following two NumPy techniques for performing element-wise multiplication.
* *
* np.multiply 
We will get the same result by using both techniques.

In [2]:
# Create a 2D matrix
a = np.array([[3,3],[3,3]])
print('Matrix a is:\n',a)
print('Shape of a is: ', a.shape, '\n')

# Create another 2D matrix
b = np.array([[6,6],[6,6]])
print('Matrix b is:\n',b)
print('Shape of b is: ', b.shape, '\n')

# Element wise multiplication using *
c = a*b
print('a*b is:\n', c, '\n')

# Element wise multiplication using np.multiply
d = np.multiply(a,b)
print('np.multiply(a,b) is:\n', d)

Matrix a is:
 [[3 3]
 [3 3]]
Shape of a is:  (2, 2) 

Matrix b is:
 [[6 6]
 [6 6]]
Shape of b is:  (2, 2) 

a*b is:
 [[18 18]
 [18 18]] 

np.multiply(a,b) is:
 [[18 18]
 [18 18]]


### Dot product:
The dot product is an algebraic operation that takes two same-sized vectors (dimension 1D) and returns a single number.

For computing a dot product between two vectors, we use the np.dot function.

The np.dot function can also be used for computing the dot product between two ndarrays (matrices). This is shown later.

In [3]:
# Create a vector
a = np.array([2, 2, 2]) 
print("Vector a: ", a)
print("Shape of a: ", a.shape, '\n')

# Create another vector
b = np.array([4, 4, 4])  
print("Vector b: ", b)
print("Shape of b:", b.shape, '\n')


# Dot product of a and b
c = np.dot(a, b) 
print("np.dot(a, b): ", c)

Vector a:  [2 2 2]
Shape of a:  (3,) 

Vector b:  [4 4 4]
Shape of b: (3,) 

np.dot(a, b):  24


### Matrix Multiplication
It is the matrix version of the dot product. Unlike the scalar-valued result of a dot product, the result of matrix multiplication is a matrix.

For performing matrix multiplication, we can use

np.matmul function
`@ operator`
<br>
The `@ operator` performs the same task the `np.matmul` performs. However, it is available only in python 3.5+

In [4]:
# Create a 2D matrix
a = np.array([[2, 2], [2, 2]]) 
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape, '\n')

# Create another 2D matrix
b = np.array([[4, 4], [4, 4]])  
print("Matrix b:\n", b)
print("\nShape of b:", b.shape, '\n')

# np.matmul
d = np.matmul(a, b)
print("np.matmul(a, b):\n", d)

# @
e = a @ b
print("\na @ b:\n", e)

Matrix a:
 [[2 2]
 [2 2]]

Shape of a:  (2, 2) 

Matrix b:
 [[4 4]
 [4 4]]

Shape of b: (2, 2) 

np.matmul(a, b):
 [[16 16]
 [16 16]]

a @ b:
 [[16 16]
 [16 16]]


### Comparison: Dot Product vs. Matrix Multiplication
The np.dot and np.matmul (and @) functions give the same result. However, there is an important difference.

The np.dot function behaves differently for matrices with dimensions higher than 2D. In such a case, np.matmul should be used.
Following guideline could be useful for selecting a suitable function.

np.dot: for computing a dot product between two 1D vectors
np.matmul and @: for computing a matrix multiplication between two matrices (2D or higher)
Example: Two 2D Matrices
We will see that np.dot, np.matmul, and @ behave similarly when the dimension of the matrices is <=2D

In [5]:
a = np.array([[2, 2], [2, 2]]) 
print("Matrix a:\n", a)
print("\nShape of a: ", a.shape)

b = np.array([[4, 4], [4, 4]])  
print("\nMatrix b:\n", b)
print("\nShape of b:", b.shape, '\n')

# np.dot
c = np.dot(a, b) 
print("np.dot(a, b):\n", c, '\n')

# np.matmul
d = np.matmul(a, b)
print("np.matmul(a, b):\n", d)

# @
e = a @ b
print("\na @ b:\n", e)

Matrix a:
 [[2 2]
 [2 2]]

Shape of a:  (2, 2)

Matrix b:
 [[4 4]
 [4 4]]

Shape of b: (2, 2) 

np.dot(a, b):
 [[16 16]
 [16 16]] 

np.matmul(a, b):
 [[16 16]
 [16 16]]

a @ b:
 [[16 16]
 [16 16]]


### Example: Two 3D Matrices
We will see that the np.dot behaves differently than np.matmul or @ when the dimension of the matrices is larger than 2D.

Note: The np.dot function works for high dimensional matrices as follows. If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

dot(a,b)[i,j,k,m]=sum(a[i,j,:]∗b[k,:,m])

In [6]:
a = np.ones(shape=(3, 2, 2), dtype=np.float32) * 2
print("Matrix a: \n", a)
print("Shape of a: ", a.shape, '\n')

b = np.ones(shape=(3, 2, 2), dtype=np.float32) * 4
print("Matrix b: \n", b)
print("Shape of b: ", b.shape, '\n')

# np.dot
c = np.dot(a, b) 
print("np.dot(a, b):\n", c)
print("Shape of np.dot(a, b): ", c.shape, '\n')

# np.matmul
d = np.matmul(a, b)
print("np.matmul(a, b):\n", d)
print("Shape of np.matmul(a, b): ", d.shape, '\n')

# @
e = a @ b
print("a @ b:\n", e)
print("Shape of a @ b: ", e.shape)

Matrix a: 
 [[[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]

 [[2. 2.]
  [2. 2.]]]
Shape of a:  (3, 2, 2) 

Matrix b: 
 [[[4. 4.]
  [4. 4.]]

 [[4. 4.]
  [4. 4.]]

 [[4. 4.]
  [4. 4.]]]
Shape of b:  (3, 2, 2) 

np.dot(a, b):
 [[[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]


 [[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]


 [[[16. 16.]
   [16. 16.]
   [16. 16.]]

  [[16. 16.]
   [16. 16.]
   [16. 16.]]]]
Shape of np.dot(a, b):  (3, 2, 3, 2) 

np.matmul(a, b):
 [[[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]]
Shape of np.matmul(a, b):  (3, 2, 2) 

a @ b:
 [[[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]

 [[16. 16.]
  [16. 16.]]]
Shape of a @ b:  (3, 2, 2)


For more reference to NumPy 3D Matrix multiplication refer to [link](https://www.geeksforgeeks.org/numpy-3d-matrix-multiplication/)


## Part B - Array broadcasting
NumPy provides a mechanism for performing mathematical operations on arrays of unequal shapes. This mechanism is known as array broadcasting or broadcasting.

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

### General Broadcasting Rules
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when

* they are equal, or
* one of them is 1

If these conditions are not met, following exception is thrown:

    ValueError: operands could not be broadcast together

It indicates that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

For more information: [link](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [7]:
'''
Dimensions of the two arrays are not compatible
'''

x = np.array([1,3,5])
y = np.array([2,4])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)

x dimension:  (3,)
y dimension:  (2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [8]:
'''
Dimensions of the two arrays are compatible
- because the dimension of the 2nd array is 1
Here, dimensions with size 1 are stretched or “copied” to match the other.
'''

x = np.array([1,3,5])
y = np.array([2,])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)

x dimension:  (3,)
y dimension:  (1,)
[3 5 7]


In [9]:
'''
Dimensions of the two arrays are compatible
- because the right-most dimensions are  equal

Here the lining up the sizes of the trailing axes of these arrays according to the broadcast rules, 
shows that they are compatible.
'''

x = np.array([[1, 3, 5], [7, 8, 9]])
y = np.array([2, 1, 3])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

print(x+y)

x dimension:  (2, 3)
y dimension:  (3,)
[[ 3  4  8]
 [ 9  9 12]]


### Outer Product
Broadcasting provides a convenient way of taking the outer product (or any other outer operation) of two arrays. The following example shows an outer addition operation of two 1-d arrays:

Here the newaxis index operator inserts a new axis into x, making it a two-dimensional (4 x 1) array. Combining the 4x1 array with y, which has shape (3, ), yields a (4 x 3) array.

In [ ]:
x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

# add a new axis
x = x[:, np.newaxis]

print("\nx dimension: ", x.shape, '\n')

print(x + y)

Alternatively, we may insert a new axis into y, making it a two-dimensional (3 x 1) array.

Then, we combine the array x with shape (4, ) with the new y, yielding a (3 x 4) array.

In [ ]:
x = np.array([0.0, 10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

print("x dimension: ", x.shape)
print("y dimension: ", y.shape)

# add a new axis
y = y[:, np.newaxis]

print("\ny dimension: ", y.shape, '\n')

print(x + y)